apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-nginx
  labels:
    app: gitops-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
